# Generated by Django 2.0.5 on 2018-05-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0002_auto_20180522_1051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='tb_emp',
        ),
    ]
